name: utility_toolset

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# DIPENDENZE: Come da requisiti e lezioni
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Per multilingua
    sdk: flutter

  # Sensori (Context-Aware)
  sensors_plus: ^7.0.0 # Per la livella [Lezione 1]

  # Persistenza Dati
  sqflite: ^2.3.3 # Per il database SQLite [Lezione 7]
  path: ^1.9.0 # Utility per sqflite

  # Temi (Diversifier)
  dynamic_color: ^1.8.0 # Per temi Material You [Lezione 4]

  # Utility
  intl: ^0.20.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# CONFIGURAZIONE FLUTTER
flutter:
  uses-material-design: true
  # Asset per la localizzazione [Lezione 4]
  assets:
    - localizable/
    - assets/images/livella_icon.png
