name: utility_toolset

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# DIPENDENZE: Come da requisiti e lezioni
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Per multilingua
    sdk: flutter

  toggle_switch: ^2.3.0

  # GEOLOCALIZZAZIONE
  geolocator: ^10.1.0

  # Sensori (Context-Aware)
  sensors_plus: ^7.0.0 # Per la livella [Lezione 1]

  # database
  sqflite: ^2.3.3 # Per il database SQLite [Lezione 7]
  path: ^1.9.0 # Utility per sqflite
  path_provider: ^2.1.2

  # Utility
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# CONFIGURAZIONE FLUTTER
flutter:
  uses-material-design: true
  # Asset per la localizzazione [Lezione 4]
  assets:
    - localizable/
    - assets/images/livella_icon.png

